# application.yml

server:
  port: 8080

spring:
  application:
    name: eureka-client-service # The name of this service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # URL of the Eureka Server
